// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotivWebApp.Data;

#nullable disable

namespace MotivWebApp.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231107200902_AddPriceField")]
    partial class AddPriceField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MotivWebApp.Models.TableAppInputRelations", b =>
                {
                    b.Property<int>("AppInputRelationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrivingLicenseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaritalStatusID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppInputRelationsID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("DrivingLicenseID");

                    b.HasIndex("MaritalStatusID");

                    b.ToTable("TableAppInputRelations");
                });

            modelBuilder.Entity("MotivWebApp.Models.TableApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicantAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicantCarPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicantDepositAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApplicantPhoneNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicantTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfRepayYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationID");

                    b.ToTable("TableApplication");
                });

            modelBuilder.Entity("MotivWebApp.Models.TableDrivingLicense", b =>
                {
                    b.Property<int>("DrivingLicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrivingLicenseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrivingLicenseID");

                    b.ToTable("TableDrivingLicense");
                });

            modelBuilder.Entity("MotivWebApp.Models.TableFinanceOptions", b =>
                {
                    b.Property<int>("FinanceOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinanceLoanRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLoanAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLoanAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("FinanceOptionID");

                    b.ToTable("TableFinanceOptions");
                });

            modelBuilder.Entity("MotivWebApp.Models.TableMaritalStatus", b =>
                {
                    b.Property<int>("MaritalStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaritalStatusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaritalStatusID");

                    b.ToTable("TableMaritalStatus");
                });

            modelBuilder.Entity("MotivWebApp.Models.TableAppInputRelations", b =>
                {
                    b.HasOne("MotivWebApp.Models.TableApplication", "TableApplication")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivWebApp.Models.TableDrivingLicense", "TableDrivingLicense")
                        .WithMany()
                        .HasForeignKey("DrivingLicenseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotivWebApp.Models.TableMaritalStatus", "TableMaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableApplication");

                    b.Navigation("TableDrivingLicense");

                    b.Navigation("TableMaritalStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
